### ISSUE TITLE
Able the "open in app" feature for Tachiyomi

### ISSUE THREAD

**Issue by Palloxin** [rev0lgenX/AniLib#12]
I heard from the developer of tachiyomi that you are the one that manage the permission of the "open in app" option so i am asking you to add it.
i don't know if it matters but it should be used here
![IMG_20220325_142441](https://user-images.githubusercontent.com/75091899/160133521-f0e923ba-aadf-4daf-aeb5-b7d092a8a9a2.jpg)
tachiyomi is the most useful app to read manga from all over the internet and it has github so i don't think it is sketchy.

**Comment by rev0lgenX** [comment]
Tachiyomi is using customtabs or browser to open the link. 'Open in app' is controlled by me but 'Open in Browser' that Tachiyomi has in its option is used to open browser which is why apps are not being listed. 
You can refer the code in Tachiyomi through the link [Open in browser code](https://github.com/tachiyomiorg/tachiyomi/blob/5c0a43e8d6e1f3fa920199c83fa6d8bd01d420ef/app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt#L282).

You can ask them to add additional option to open app instead of browser.

**Comment by Palloxin** [comment]
This is what they said:
![Screenshot_20220325-151347](https://user-images.githubusercontent.com/75091899/160137606-dfced14d-4eb1-444e-a8ac-81e7d365bab1.jpg)
https://github.com/tachiyomiorg/tachiyomi/issues/6819

**Comment by rev0lgenX** [comment]
[code link](https://github.com/tachiyomiorg/tachiyomi/blob/5c0a43e8d6e1f3fa920199c83fa6d8bd01d420ef/app/src/main/java/eu/kanade/tachiyomi/util/system/ContextExtensions.kt#L282)
Use this link and ask them if this code is being used to open link. If this code is used then it directly opens browser, and tell them you want something like
```

fun Context.openLink(url: String?) {
    try {
        if (!url.isNullOrBlank()) {
            startActivity(Intent(Intent.ACTION_VIEW, url.trim().toUri()).also {
                it.flags = Intent.FLAG_ACTIVITY_NEW_TASK
            })
        } else {
           
        }
    } catch (e: Exception) {
    }
}

Deep linking is not possible but above code will list all the app that can handle the link.
```

**Comment by Palloxin** [comment]
revolgen try to speak there pls, i can't be the intermediator, it is strange and they might ban me if i insist since i am not a directly involved

**Comment by rev0lgenX** [comment]
Clicking on "Open in browser" does shows the apps that are are able to handle the link. But, if any browser is 'Set as Default' then this options will no longer be available, and they'll have to remove default browser to show the list of app again. 

They locked the issue, I can't add comment to it.

**Comment by Palloxin** [comment]
> Clicking on "Open in browser" does shows the apps that are are able to handle the link. But, if any browser is 'Set as Default' then this options will no longer be available, and they'll have to remove default browser to show the list of app again.
> 
> They locked the issue, I can't add comment to it. You can try to remove your default browser and try again, it should show app list.

a mod reopened it, you can debate there

**Comment by rev0lgenX** [comment]
@Palloxin  They opened it, I hope you'll get what you wanted.✌️✌️
