### ISSUE TITLE
Feature Request: chapter tracker for manga in releasing status

### ISSUE THREAD

**Issue by Palloxin** [rev0lgenX/AniLib#16]
a tracker that allows to see how many chapters a manga has avaiable on the internet while in its releasing state.
you can get this information from a website that does it pretty well called anime-planet. i know it will not be possible to search manga in releasing status using this information (the number of chapter took from animeplanet) but it would be good if this information would be added when visiting directly a manga: 
![IMG_20220403_190736](https://user-images.githubusercontent.com/75091899/161439493-5c35fa68-8e5d-4ce2-94f3-3586cf1a38d5.jpg)
instead of the "?" put the number of chapter avaiable got from the website animeplanet.
This feature should be toggleable from the settings

**Comment by rev0lgenX** [comment]
I can't find any official plugable API related to anime-planet that would help me integrate this feature, neither could I find any other website to help me achieve this. If you could find any website that provides official API (which has direct link to MAL or AniList), to give such info, please open this issue again. I'll close this for now.

**Comment by Palloxin** [comment]
Can't the app just "rob" (or scrape) this information and put it on the app?

**Comment by rev0lgenX** [comment]
It is possible but since there is no directly link with MAL or AniList, the information is not guaranteed to return correctly, since I can't use id. Plus it would be considered illegal to scrape and google(playstore) might not be happy with it if they found out.

**Comment by Palloxin** [comment]
since it is possible i have another suggestion.
take the data from the social section and use that to roughly deduce the number of chapters avaiable on internet. usually i.check the social section to look for the highest chapter read by users. obviously this number should be constant, like a lot of user  should.have read  the chapter 75. you could take the number and do 75-3=72~( 3 a fixed number) just to be roughly there since it might not be precise and this number should be just a reference to understand how many chapter a.manga has.

**Comment by rev0lgenX** [comment]
Sorry, but I won't be implementing that way. But I can add small activity section in to the overview to get the recent activity, like the character section in overview.
