### ISSUE TITLE
[Feature request]  add sorting by mean score

### ISSUE THREAD

**Issue by Palloxin** [rev0lgenX/AniLib#18]
![immagine](https://user-images.githubusercontent.com/75091899/161512624-0ad3820c-1cf3-448b-9b11-3e27d402f27f.png)
can you add a sort option for the "mean score"? the "Score" on the app sorts only by "average score".

**Comment by rev0lgenX** [comment]
Sorry but these are only the sorts provided by AniList. You can look into the docs and confirm it yourself.

link: https://anilist.github.io/ApiV2-GraphQL-Docs/

Search for MediaSort
