### ISSUE TITLE
[Feature request] Chapter filter

### ISSUE THREAD

**Issue by Palloxin** [rev0lgenX/AniLib#19]
![immagine](https://user-images.githubusercontent.com/75091899/161512924-e36c7caf-de26-4742-b2b0-f30783256d4c.png)

when i want a manga with minimum of 75 chapters  the app fixes the max chapters automatically at 500 and i don't want it. i am asking if you could make the app keep the ∞ as a maximum if not touched. maybe adding an additional step that is 498 then 499 then 500 then ∞ so as not to exclude mangas with more than 500 chapters.

**Comment by rev0lgenX** [comment]
![Screenshot_20220404-150214_AniLib](https://user-images.githubusercontent.com/20517801/161513848-3c4aa980-6fee-46d3-a1d0-bcd7f960fd64.jpg)

I added this for this issue.

**Comment by rev0lgenX** [comment]
This will do. Closing the issue. 
Duplicate #22
