### ISSUE TITLE
[Feature request] Hentai filter for manga/anime list section

### ISSUE THREAD

**Issue by Palloxin** [rev0lgenX/AniLib#24]
![immagine](https://user-images.githubusercontent.com/75091899/161516873-4bc8e4bf-7de3-45d5-9582-0823f1d0bfb5.png)
can you add a button to exclude/include/neutral the hentai stuff in the manga/anime list? it is the one similar to the new hentai button on the search filter.

**Comment by rev0lgenX** [comment]
![Screenshot_20220404-152420_AniLib](https://user-images.githubusercontent.com/20517801/161517757-e8be91f2-7dc3-451f-a693-c1ac63646e0f.jpg)
Will be available in 1.1.14, dont know how long playstore is gonna take.
