### ISSUE TITLE
[Bug] "Share" button not working

### ISSUE THREAD

**Issue by Palloxin** [rev0lgenX/AniLib#33]
https://user-images.githubusercontent.com/75091899/162567331-cf723c0f-00da-4e03-aeb9-a518ffd02895.mp4

Maybe i mistook that function for something else but the share option brings me back to the manga page. Usually the app on my phone use "Huawei Share" as a transit point, maybe it can help.
Android 8
Huawei p8 lite 2017

**Comment by rev0lgenX** [comment]
I think you kept default app as AniLib to handle the link, you need to remove default for it to work.

**Comment by Palloxin** [comment]
I just tested it. that button doesn't do anything useful. tell me if i am mistaken but when i saw "share" i thought it would share the link of that manga elsewhere (discord, whatsapp, telegram.. elsewhere) but when i clicked on it only the browser and anilib showed up, and the one on the browser brought me at the same manga on the website. so i am asking what is the point of that button? it doesn't "share" nothing.
