### ISSUE TITLE
Request to resize "relation" section

### ISSUE THREAD

**Issue by AgentElixir** [rev0lgenX/AniLib#36]
Relations section shows the thumbnail really big and cuts off some of the image
![Screenshot_20220413-222049](https://user-images.githubusercontent.com/88673750/163233394-9921b0cf-f0b9-499d-9365-2e94d9c9606b.jpg)
it will be easy to oversee all realated anime in small size like in recommendation section
![Screenshot_20220413-222103](https://user-images.githubusercontent.com/88673750/163233428-65b72ae1-78eb-428f-942d-70b4fab7c910.jpg)

**Comment by natsuthelight** [comment]
I m agree with u
