### ISSUE TITLE
[Bug] start date shows as ? when only year is known

### ISSUE THREAD

**Issue by Frain-Breeze** [rev0lgenX/AniLib#47]
take the anime https://anilist.co/anime/131516 for example, which is set to release somewhere in 2022, as anilist wil show you: ![Screenshot_20220520-073125_1.png](https://user-images.githubusercontent.com/43963404/169457380-d740b3be-650a-4d9a-ac1c-76c992a1345f.png)

however, anilib will just show you a '?' for the date instead: ![Screenshot_20220520-073556_1.png](https://user-images.githubusercontent.com/43963404/169457912-1cb8c140-6f5d-4e5b-813c-0a8e923e8421.png)

as always, thank you for the great app!

**Comment by rev0lgenX** [comment]
fixed in new release
