### ISSUE TITLE
Add Turkish language

### ISSUE THREAD

**Issue by kyoyacchi** [rev0lgenX/AniLib#48]
I want to translate Turkish language but there's no Turkish in POEditor. Could you add that language?

**Comment by rev0lgenX** [comment]
Done.

**Comment by kyoyacchi** [comment]
> Done.

Also, can you accept my join request?

**Comment by kyoyacchi** [comment]
> Done.

I translated 94.29% of it.

**Comment by rev0lgenX** [comment]
It's done, you can find apk from the link to test it out.

https://github.com/rev0lgenX/AniLib-Snapshot/releases/tag/S-753
