### ISSUE TITLE
FEATURE AND ISSUE

### ISSUE THREAD

**Issue by natsuthelight** [rev0lgenX/AniLib#49]
In voice rôles section of voice Actors : 

- [x] - Can u change the display mode ? Put a display by line it's much more aesthetic.

    ![image](https://user-images.githubusercontent.com/79458536/171621376-df253723-a1ab-4cf1-885b-2064698bbdb8.png)

- [ ] - Could you also add sorting based on characters? Thus we will not see several times the same characters.

   ![image](https://user-images.githubusercontent.com/79458536/171621919-cfe48180-3df2-4965-9aec-df842a88a6da.png)

In character section : 

- [x] - There is a problem with this display. When we try to click in the middle (in the part in gray) nothing happens. Can you fix this and make clicking in the middle do the same thing as clicking on the image of the character on the left.

   ![image](https://user-images.githubusercontent.com/79458536/171622088-7621e1d7-338f-455e-904d-7f86016f69e5.png)

- [x] - Can you rearrange the display as below ? ("japanease" is not necessary because it is already indicated above but you can leave it if you want)

   ![image](https://user-images.githubusercontent.com/79458536/171625525-77122439-310d-45bf-9ef7-1cee4df3408b.png)

**Comment by rev0lgenX** [comment]
Grouping based on characters, unfortunately can't sort it by character name, right now sorts with `character id` by default.
