### ISSUE TITLE
[Bug] Can't login to Anilist account on AniLib Snapshot

### ISSUE THREAD

**Issue by kyoyacchi** [rev0lgenX/AniLib#54]
Hi.
I can't login to my Anilist account on anilib *latest* snapshot version
I tried older versions but still same.

Normal one doesn't have same problem.

It just says "Authenticating". Nothing else happens even if i clear data and try again.

https://user-images.githubusercontent.com/63583961/174100581-295046ab-62ae-4cd9-ac1b-d38eee9466a8.mp4

**Comment by rev0lgenX** [comment]
@kyoyacchi Done
https://github.com/rev0lgenX/AniLib/releases/tag/v1.1.13

**Comment by rev0lgenX** [comment]
Which name should I use for contributor name? I have written `kyoya`  for now. Also do you want to link your anilist account to the contributor section?

**Comment by rev0lgenX** [comment]
Okay
