### ISSUE TITLE
bug: some shows do not appear in list

### ISSUE THREAD

**Issue by Frain-Breeze** [rev0lgenX/AniLib#58]
recently i set https://anilist.co/anime/131548 to rewatching, but the show didn't appear in the rewatch list (see ![here](https://user-images.githubusercontent.com/43963404/182043174-6764887b-3ec9-42e3-91c0-6aab06f27a5f.png) ). both gunsmith cats and hidamari sketch were set to rewatching after akebi, so it only happens for a few shows. just now, the same happened when I set https://anilist.co/anime/5671 to watching, and this also didn't show up. they come up in search results and I can update them just fine, though. my list is https://anilist.co/user/426456 and I'm running anilist version 1.1.17

**Comment by rev0lgenX** [comment]
Right now after changing status of anime or adding to the list wont automatically update the list right away, you need to pull down to refresh to see new changes. I can see your changes, so I think its working fine.


![Screenshot_20220801-075701_AniLib.jpg](https://user-images.githubusercontent.com/20517801/182059440-4beae1c8-e30e-48f4-99b6-318e45b9ba1a.jpg)

**Comment by Frain-Breeze** [comment]
refreshing didn't do much, but logging out and in again did fix it.
