### ISSUE TITLE
Yuri tags is missing on search filter

### ISSUE THREAD

**Issue by HoriKyoukosimp** [rev0lgenX/AniLib#59]
I dont know what to put here because the title already says it all 💀

**Comment by rev0lgenX** [comment]
You can add any missing tags from `Settings-> Filter->tags`. After that it will appear in search filter.

**Comment by HoriKyoukosimp** [comment]
There is no way that thing exist

Ur anilist client is the best 👍

**Comment by rev0lgenX** [comment]
Thank You.
