### ISSUE TITLE
[social tab] description text doesn't adapt to action

### ISSUE THREAD

**Issue by Frain-Breeze** [rev0lgenX/AniLib#6]
as can be seen in the following screenshot... ![Screenshot_20211117-170949~2](https://user-images.githubusercontent.com/43963404/142237733-cc6e53b1-ffd9-44b6-bf23-e51162cf72b5.png)
...the bubbles in the social tab don't adjust to the action they're showing. they always follow the "watched episode <x> of <y>" format, which only works for, well, watching an episode. the text should change depending on whether you are adding a show to your list, dropping one, etc.

**Comment by rev0lgenX** [comment]
Fixed in v1.1.12
