### ISSUE TITLE
Airing anime not showing

### ISSUE THREAD

**Issue by noaccOS** [rev0lgenX/AniLib#66]
I have a few anime in progress, some currently airing and some finished.

However in the app I can only see "Finished" anime. The count shown for "watching" is correct but then only the finished entries are present in the list.

Airing titles also aren't present even in the "All" category
![photo_2022-10-30_22-28-23](https://user-images.githubusercontent.com/24324352/198902677-d6cc3b18-5a63-440e-aa04-f81a2c32f55d.jpg)

**Comment by rev0lgenX** [comment]
@noaccOS Hi, could you provide me with your anilist username?

**Comment by noaccOS** [comment]
> @noaccOS Hi, could you provide me with your anilist username?

Same as on here, here's a direct link to it https://anilist.co/user/noaccOS/

**Comment by rev0lgenX** [comment]
I think its working fine. 

![Screenshot_20221118-204800_AniLib](https://user-images.githubusercontent.com/20517801/202735551-e168ef1c-f34d-4189-a1a9-915e032a3970.jpg)


I guess you applied some filter, the filter are saved even when you close the app so can you check if you have applied the filter.

![Screenshot_20221118-204927_AniLib](https://user-images.githubusercontent.com/20517801/202735741-985310ef-3ce3-4e56-a703-518201dad001.jpg)

**Comment by noaccOS** [comment]
Yeah that was it. I did try logging out and back in but it seems like the filter persisted anyway. 
Thank you for your help and sorry for the false issue
