### ISSUE TITLE
App not working 

### ISSUE THREAD

**Issue by YouSummoner** [rev0lgenX/AniLib#67]
Every section in the app is showing "something went wrong" error.
I even tried reinstalling the app but it's no use.

**Comment by rev0lgenX** [comment]
The main problem is with the AniList API, I think they are having server issues. Here is a recent tweet by them.

https://twitter.com/AniListco/status/1591127717130686464?t=KRcyLsoO49u43sHhW5zlYQ&s=19

I think other app is also having similar problem. This is screenshot from Alchan and Otraku.
![Screenshot_20221113-073533](https://user-images.githubusercontent.com/20517801/201501881-2881ba2d-e58a-41ec-9fb3-c8e141dda422.jpg)
![Screenshot_20221113-073528_AL-chan](https://user-images.githubusercontent.com/20517801/201501882-d0177713-2ba9-4b25-87b8-4895e17fa4bc.jpg)



All we can do is wait for a little bit.

**Comment by YouSummoner** [comment]
Otraku has started working for quite some time now, but Anilib still hasn't...

**Comment by rev0lgenX** [comment]
![Screenshot_20221114-011752](https://user-images.githubusercontent.com/20517801/201540613-96fea3eb-b7bd-4e44-b274-d972ff55e927.jpg)


Mine is still the same.

**Comment by YouSummoner** [comment]
> ![Screenshot_20221114-011752](https://user-images.githubusercontent.com/20517801/201540613-96fea3eb-b7bd-4e44-b274-d972ff55e927.jpg)
> 
> 
> Mine is still the same.

![Screenshot_20221114-010644_Otraku.png](https://user-images.githubusercontent.com/107224555/201540768-c14ffe94-0e60-40c2-afc9-f3acba3bbd78.png)
