### ISSUE TITLE
Something went wrong 

### ISSUE THREAD

**Issue by hhsyhhsy** [rev0lgenX/AniLib#68]
Whenever I try to open the app it shows the error (as shown in the video). Tried the basic troubleshooting and reinstalled the app but the issue persists.

Note:After several attempts it becomes normal but again it is reverted back to the previous error.

https://user-images.githubusercontent.com/102210195/201506972-b715a820-0aa5-4faf-9e0a-2146a94cee34.mp4

**Comment by rev0lgenX** [comment]
Related #67. 

Currently, it seems there is problem with AniList API. Please follow their tweet for updates. It should automatically resolve afterwards.  

https://twitter.com/AniListco/status/1591127717130686464?t=KRcyLsoO49u43sHhW5zlYQ&s=19
