### ISSUE TITLE
Widget settings not working

### ISSUE THREAD

**Issue by Zaryuu** [rev0lgenX/AniLib#7]
Device: Oneplus 7 Pro
Android Version: 11
OxygenOS Build No:  11.0.5.1.GM21BA
App Version: 1.1.11

The issue ist, that the Widget settings won't save at all.
If you change something it won't save, doesn't Matter If the widget ist active on Home Screen or not.
The Widget itself ist working, but not configurable.

**Comment by rev0lgenX** [comment]
Fixed in v1.1.12
