### ISSUE TITLE
Wrong information

### ISSUE THREAD

**Issue by natsuthelight** [rev0lgenX/AniLib#8]
Device : Samsung S21
OS :  One UI 4.0 (Android 12)

When I leave the application and come back after several hours, a lot of information is incorrect, such as the "Airing Schedules" section which does not take into account the filters activated when they are activated. There is also the Seasons section which does not display the correct season anime. And I think there is another section too.
But when I completely quit the application (not just by pressing the home button) and return to the application, everything is back to normal.

I can send you pictures on discord but you're not too active on it anymore

**Comment by MrJako2001** [comment]
The same thing happens to me.
