### ISSUE TITLE
No Notifications on Android 13 

### ISSUE THREAD

**Issue by YouSummoner** [rev0lgenX/AniLib#83]
The app doesn't send any notifications on Android 13, it doesn't even prompt the user to allow sending notifications as required by Android 13. 

Please update the app to properly support Android 13...

**Comment by YouSummoner** [comment]
Umm, so is proper Android 13 support in development?
When can we expect to receive an update...

**Comment by rev0lgenX** [comment]
Sorry for the issue, I upgraded to 13+ in a hurry, I know that its not properly supported, but I am trying to migrate my app to newer compose design. You can see the migration in v3 branch and I am writing everything from scratch. Its of kind of real slow migration dont know when it will end. Meanwhile I will update current notif issue in 13+. And will focus on only solving issue in current app, and slowly migrate to v3. For now I will close it and tag the issue after resolving.

**Comment by YouSummoner** [comment]
Thanks for the clarification 👍

**Comment by rev0lgenX** [comment]
Anyway even if its incomplete if you like to check new migrated app you can download it from here https://app.bitrise.io/artifact/210845569/p/f39656eac90458a264e5a7d47ff6ea42. 🙂🙂

**Comment by YouSummoner** [comment]
WOW, thanks a bunch 😋. Looking really good so far, it's even smooth and all. Just noticed something, don't you think the scaling in the anime info pages is just a bit much.
Like the (i) button next to the tags isn't inclined with the text and the external links are looking really big and their text has a weird shadow effect... Else it's working really well.

**Comment by rev0lgenX** [comment]
Thanks for pointing the tag inlining, as for link, I dont want to calculate text color based on each link background right now so added shadow effect, anyway thanks for trying it out.

**Comment by Whisperx17** [comment]
> Thanks for pointing the tag inlining, as for link, I dont want to calculate text color based on each link background right now so added shadow effect, anyway thanks for trying it out.

Hello. Accidentally found the new Anilib app while trying to report an issue. It's looking good so far. If you need help with reviews on the new features you're implementing, let me know where I can leave them

**Comment by YouSummoner** [comment]
Hey, just wanted to ask if the v3 migration is still in progress because there hasn't been any new changes in that branch. Do you have any timeline as to when we can expect to see the new app, really looking forward to it. 😊
